apiVersion: v1
kind: Service
metadata:
  name: hellofrontendservice
  labels:
    app: hello
    tier: frontend
spec:
  type: NodePort
  selector:
    app: hello
    tier: frontend
  ports:
    - port: 80
      nodePort: 30080
      name: http