apiVersion: v1
kind: Service
metadata:
  name: hellobackendservice
  labels:
    app: hello
    tier: backend
spec:
  type: ClusterIP
  selector:
    app: hello
    tier: backend
  ports:
    - port: 8080
      name: http